[package]
name = "gfaas"
version = "0.1.0"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[dependencies]
gfaas-macro = { path = "crates/macro" }
anyhow = "1"
zip = "0.5"
serde_json = "1"
tempfile = "3.1"
tokio = { version = "0.2", features = ["blocking"] }
wasi-rt = { git = "https://github.com/golemfactory/ya-runtime-wasi.git", package = "ya-runtime-wasi" }

[workspace]
members = [
    "crates/cli",
]
exclude = [
    "examples/hello",
    "examples/sum",
]
